apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: cloudwatch-test
  name: cloudwatch-test
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: cloudwatch-test:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/RedHatInsights/cloudwatch-test
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.6
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
